<?php
/**
 * ArticleMe
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Bitween\DevTo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DEV API (beta)
 *
 * Access Forem articles, users and other resources via API.  For a real-world example of Forem in action, check out [DEV](https://www.dev.to).  All endpoints that don't require authentication are CORS enabled.  Dates and date times, unless otherwise specified, must be in the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 0.9.5
 * Contact: yo@dev.to
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bitween\DevTo\Model;

use \ArrayAccess;
use \Bitween\DevTo\ObjectSerializer;

/**
 * ArticleMe Class Doc Comment
 *
 * @category Class
 * @package  Bitween\DevTo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class ArticleMe implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ArticleMe';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'typeOf' => 'string',
        'id' => 'int',
        'title' => 'string',
        'description' => 'string',
        'coverImage' => 'string',
        'published' => 'bool',
        'publishedAt' => '\DateTime',
        'tagList' => 'string[]',
        'slug' => 'string',
        'path' => 'string',
        'url' => 'string',
        'canonicalUrl' => 'string',
        'commentsCount' => 'int',
        'positiveReactionsCount' => 'int',
        'publicReactionsCount' => 'int',
        'pageViewsCount' => 'int',
        'publishedTimestamp' => '\DateTime',
        'bodyMarkdown' => 'string',
        'user' => '\Bitween\DevTo\Model\SharedUser',
        'organization' => '\Bitween\DevTo\Model\SharedOrganization',
        'flareTag' => '\Bitween\DevTo\Model\ArticleFlareTag'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'typeOf' => null,
        'id' => 'int32',
        'title' => null,
        'description' => null,
        'coverImage' => 'url',
        'published' => null,
        'publishedAt' => 'date-time',
        'tagList' => null,
        'slug' => null,
        'path' => 'path',
        'url' => 'url',
        'canonicalUrl' => 'url',
        'commentsCount' => 'int32',
        'positiveReactionsCount' => 'int32',
        'publicReactionsCount' => 'int32',
        'pageViewsCount' => 'int32',
        'publishedTimestamp' => 'date-time',
        'bodyMarkdown' => null,
        'user' => null,
        'organization' => null,
        'flareTag' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'typeOf' => 'type_of',
        'id' => 'id',
        'title' => 'title',
        'description' => 'description',
        'coverImage' => 'cover_image',
        'published' => 'published',
        'publishedAt' => 'published_at',
        'tagList' => 'tag_list',
        'slug' => 'slug',
        'path' => 'path',
        'url' => 'url',
        'canonicalUrl' => 'canonical_url',
        'commentsCount' => 'comments_count',
        'positiveReactionsCount' => 'positive_reactions_count',
        'publicReactionsCount' => 'public_reactions_count',
        'pageViewsCount' => 'page_views_count',
        'publishedTimestamp' => 'published_timestamp',
        'bodyMarkdown' => 'body_markdown',
        'user' => 'user',
        'organization' => 'organization',
        'flareTag' => 'flare_tag'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'typeOf' => 'setTypeOf',
        'id' => 'setId',
        'title' => 'setTitle',
        'description' => 'setDescription',
        'coverImage' => 'setCoverImage',
        'published' => 'setPublished',
        'publishedAt' => 'setPublishedAt',
        'tagList' => 'setTagList',
        'slug' => 'setSlug',
        'path' => 'setPath',
        'url' => 'setUrl',
        'canonicalUrl' => 'setCanonicalUrl',
        'commentsCount' => 'setCommentsCount',
        'positiveReactionsCount' => 'setPositiveReactionsCount',
        'publicReactionsCount' => 'setPublicReactionsCount',
        'pageViewsCount' => 'setPageViewsCount',
        'publishedTimestamp' => 'setPublishedTimestamp',
        'bodyMarkdown' => 'setBodyMarkdown',
        'user' => 'setUser',
        'organization' => 'setOrganization',
        'flareTag' => 'setFlareTag'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'typeOf' => 'getTypeOf',
        'id' => 'getId',
        'title' => 'getTitle',
        'description' => 'getDescription',
        'coverImage' => 'getCoverImage',
        'published' => 'getPublished',
        'publishedAt' => 'getPublishedAt',
        'tagList' => 'getTagList',
        'slug' => 'getSlug',
        'path' => 'getPath',
        'url' => 'getUrl',
        'canonicalUrl' => 'getCanonicalUrl',
        'commentsCount' => 'getCommentsCount',
        'positiveReactionsCount' => 'getPositiveReactionsCount',
        'publicReactionsCount' => 'getPublicReactionsCount',
        'pageViewsCount' => 'getPageViewsCount',
        'publishedTimestamp' => 'getPublishedTimestamp',
        'bodyMarkdown' => 'getBodyMarkdown',
        'user' => 'getUser',
        'organization' => 'getOrganization',
        'flareTag' => 'getFlareTag'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['typeOf'] = $data['typeOf'] ?? null;
        $this->container['id'] = $data['id'] ?? null;
        $this->container['title'] = $data['title'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
        $this->container['coverImage'] = $data['coverImage'] ?? null;
        $this->container['published'] = $data['published'] ?? null;
        $this->container['publishedAt'] = $data['publishedAt'] ?? null;
        $this->container['tagList'] = $data['tagList'] ?? null;
        $this->container['slug'] = $data['slug'] ?? null;
        $this->container['path'] = $data['path'] ?? null;
        $this->container['url'] = $data['url'] ?? null;
        $this->container['canonicalUrl'] = $data['canonicalUrl'] ?? null;
        $this->container['commentsCount'] = $data['commentsCount'] ?? null;
        $this->container['positiveReactionsCount'] = $data['positiveReactionsCount'] ?? null;
        $this->container['publicReactionsCount'] = $data['publicReactionsCount'] ?? null;
        $this->container['pageViewsCount'] = $data['pageViewsCount'] ?? null;
        $this->container['publishedTimestamp'] = $data['publishedTimestamp'] ?? null;
        $this->container['bodyMarkdown'] = $data['bodyMarkdown'] ?? null;
        $this->container['user'] = $data['user'] ?? null;
        $this->container['organization'] = $data['organization'] ?? null;
        $this->container['flareTag'] = $data['flareTag'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['typeOf'] === null) {
            $invalidProperties[] = "'typeOf' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['coverImage'] === null) {
            $invalidProperties[] = "'coverImage' can't be null";
        }
        if ($this->container['published'] === null) {
            $invalidProperties[] = "'published' can't be null";
        }
        if ($this->container['publishedAt'] === null) {
            $invalidProperties[] = "'publishedAt' can't be null";
        }
        if ($this->container['tagList'] === null) {
            $invalidProperties[] = "'tagList' can't be null";
        }
        if ($this->container['slug'] === null) {
            $invalidProperties[] = "'slug' can't be null";
        }
        if ($this->container['path'] === null) {
            $invalidProperties[] = "'path' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ($this->container['canonicalUrl'] === null) {
            $invalidProperties[] = "'canonicalUrl' can't be null";
        }
        if ($this->container['commentsCount'] === null) {
            $invalidProperties[] = "'commentsCount' can't be null";
        }
        if ($this->container['positiveReactionsCount'] === null) {
            $invalidProperties[] = "'positiveReactionsCount' can't be null";
        }
        if ($this->container['publicReactionsCount'] === null) {
            $invalidProperties[] = "'publicReactionsCount' can't be null";
        }
        if ($this->container['pageViewsCount'] === null) {
            $invalidProperties[] = "'pageViewsCount' can't be null";
        }
        if ($this->container['publishedTimestamp'] === null) {
            $invalidProperties[] = "'publishedTimestamp' can't be null";
        }
        if ($this->container['bodyMarkdown'] === null) {
            $invalidProperties[] = "'bodyMarkdown' can't be null";
        }
        if ($this->container['user'] === null) {
            $invalidProperties[] = "'user' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets typeOf
     *
     * @return string
     */
    public function getTypeOf()
    {
        return $this->container['typeOf'];
    }

    /**
     * Sets typeOf
     *
     * @param string $typeOf typeOf
     *
     * @return self
     */
    public function setTypeOf($typeOf)
    {
        $this->container['typeOf'] = $typeOf;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets coverImage
     *
     * @return string
     */
    public function getCoverImage()
    {
        return $this->container['coverImage'];
    }

    /**
     * Sets coverImage
     *
     * @param string $coverImage coverImage
     *
     * @return self
     */
    public function setCoverImage($coverImage)
    {
        $this->container['coverImage'] = $coverImage;

        return $this;
    }

    /**
     * Gets published
     *
     * @return bool
     */
    public function getPublished()
    {
        return $this->container['published'];
    }

    /**
     * Sets published
     *
     * @param bool $published published
     *
     * @return self
     */
    public function setPublished($published)
    {
        $this->container['published'] = $published;

        return $this;
    }

    /**
     * Gets publishedAt
     *
     * @return \DateTime
     */
    public function getPublishedAt()
    {
        return $this->container['publishedAt'];
    }

    /**
     * Sets publishedAt
     *
     * @param \DateTime $publishedAt publishedAt
     *
     * @return self
     */
    public function setPublishedAt($publishedAt)
    {
        $this->container['publishedAt'] = $publishedAt;

        return $this;
    }

    /**
     * Gets tagList
     *
     * @return string[]
     */
    public function getTagList()
    {
        return $this->container['tagList'];
    }

    /**
     * Sets tagList
     *
     * @param string[] $tagList tagList
     *
     * @return self
     */
    public function setTagList($tagList)
    {
        $this->container['tagList'] = $tagList;

        return $this;
    }

    /**
     * Gets slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->container['slug'];
    }

    /**
     * Sets slug
     *
     * @param string $slug slug
     *
     * @return self
     */
    public function setSlug($slug)
    {
        $this->container['slug'] = $slug;

        return $this;
    }

    /**
     * Gets path
     *
     * @return string
     */
    public function getPath()
    {
        return $this->container['path'];
    }

    /**
     * Sets path
     *
     * @param string $path path
     *
     * @return self
     */
    public function setPath($path)
    {
        $this->container['path'] = $path;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets canonicalUrl
     *
     * @return string
     */
    public function getCanonicalUrl()
    {
        return $this->container['canonicalUrl'];
    }

    /**
     * Sets canonicalUrl
     *
     * @param string $canonicalUrl canonicalUrl
     *
     * @return self
     */
    public function setCanonicalUrl($canonicalUrl)
    {
        $this->container['canonicalUrl'] = $canonicalUrl;

        return $this;
    }

    /**
     * Gets commentsCount
     *
     * @return int
     */
    public function getCommentsCount()
    {
        return $this->container['commentsCount'];
    }

    /**
     * Sets commentsCount
     *
     * @param int $commentsCount commentsCount
     *
     * @return self
     */
    public function setCommentsCount($commentsCount)
    {
        $this->container['commentsCount'] = $commentsCount;

        return $this;
    }

    /**
     * Gets positiveReactionsCount
     *
     * @return int
     */
    public function getPositiveReactionsCount()
    {
        return $this->container['positiveReactionsCount'];
    }

    /**
     * Sets positiveReactionsCount
     *
     * @param int $positiveReactionsCount positiveReactionsCount
     *
     * @return self
     */
    public function setPositiveReactionsCount($positiveReactionsCount)
    {
        $this->container['positiveReactionsCount'] = $positiveReactionsCount;

        return $this;
    }

    /**
     * Gets publicReactionsCount
     *
     * @return int
     */
    public function getPublicReactionsCount()
    {
        return $this->container['publicReactionsCount'];
    }

    /**
     * Sets publicReactionsCount
     *
     * @param int $publicReactionsCount publicReactionsCount
     *
     * @return self
     */
    public function setPublicReactionsCount($publicReactionsCount)
    {
        $this->container['publicReactionsCount'] = $publicReactionsCount;

        return $this;
    }

    /**
     * Gets pageViewsCount
     *
     * @return int
     */
    public function getPageViewsCount()
    {
        return $this->container['pageViewsCount'];
    }

    /**
     * Sets pageViewsCount
     *
     * @param int $pageViewsCount pageViewsCount
     *
     * @return self
     */
    public function setPageViewsCount($pageViewsCount)
    {
        $this->container['pageViewsCount'] = $pageViewsCount;

        return $this;
    }

    /**
     * Gets publishedTimestamp
     *
     * @return \DateTime
     */
    public function getPublishedTimestamp()
    {
        return $this->container['publishedTimestamp'];
    }

    /**
     * Sets publishedTimestamp
     *
     * @param \DateTime $publishedTimestamp Crossposting or published date time
     *
     * @return self
     */
    public function setPublishedTimestamp($publishedTimestamp)
    {
        $this->container['publishedTimestamp'] = $publishedTimestamp;

        return $this;
    }

    /**
     * Gets bodyMarkdown
     *
     * @return string
     */
    public function getBodyMarkdown()
    {
        return $this->container['bodyMarkdown'];
    }

    /**
     * Sets bodyMarkdown
     *
     * @param string $bodyMarkdown The body of the article in Markdown format
     *
     * @return self
     */
    public function setBodyMarkdown($bodyMarkdown)
    {
        $this->container['bodyMarkdown'] = $bodyMarkdown;

        return $this;
    }

    /**
     * Gets user
     *
     * @return \Bitween\DevTo\Model\SharedUser
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param \Bitween\DevTo\Model\SharedUser $user user
     *
     * @return self
     */
    public function setUser($user)
    {
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets organization
     *
     * @return \Bitween\DevTo\Model\SharedOrganization|null
     */
    public function getOrganization()
    {
        return $this->container['organization'];
    }

    /**
     * Sets organization
     *
     * @param \Bitween\DevTo\Model\SharedOrganization|null $organization organization
     *
     * @return self
     */
    public function setOrganization($organization)
    {
        $this->container['organization'] = $organization;

        return $this;
    }

    /**
     * Gets flareTag
     *
     * @return \Bitween\DevTo\Model\ArticleFlareTag|null
     */
    public function getFlareTag()
    {
        return $this->container['flareTag'];
    }

    /**
     * Sets flareTag
     *
     * @param \Bitween\DevTo\Model\ArticleFlareTag|null $flareTag flareTag
     *
     * @return self
     */
    public function setFlareTag($flareTag)
    {
        $this->container['flareTag'] = $flareTag;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


