<?php
/**
 * Organization
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Bitween\DevTo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DEV API (beta)
 *
 * Access Forem articles, users and other resources via API.  For a real-world example of Forem in action, check out [DEV](https://www.dev.to).  All endpoints that don't require authentication are CORS enabled.  Dates and date times, unless otherwise specified, must be in the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 0.9.5
 * Contact: yo@dev.to
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bitween\DevTo\Model;

use \ArrayAccess;
use \Bitween\DevTo\ObjectSerializer;

/**
 * Organization Class Doc Comment
 *
 * @category Class
 * @description Organization
 * @package  Bitween\DevTo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class Organization implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Organization';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'typeOf' => 'string',
        'username' => 'string',
        'name' => 'string',
        'summary' => 'string',
        'twitterUsername' => 'string',
        'githubUsername' => 'string',
        'url' => 'string',
        'location' => 'string',
        'techStack' => 'string',
        'tagLine' => 'string',
        'story' => 'string',
        'joinedAt' => '\DateTime',
        'profileImage' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'typeOf' => null,
        'username' => null,
        'name' => null,
        'summary' => null,
        'twitterUsername' => null,
        'githubUsername' => null,
        'url' => 'url',
        'location' => null,
        'techStack' => null,
        'tagLine' => null,
        'story' => null,
        'joinedAt' => 'date-time',
        'profileImage' => 'url'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'typeOf' => 'type_of',
        'username' => 'username',
        'name' => 'name',
        'summary' => 'summary',
        'twitterUsername' => 'twitter_username',
        'githubUsername' => 'github_username',
        'url' => 'url',
        'location' => 'location',
        'techStack' => 'tech_stack',
        'tagLine' => 'tag_line',
        'story' => 'story',
        'joinedAt' => 'joined_at',
        'profileImage' => 'profile_image'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'typeOf' => 'setTypeOf',
        'username' => 'setUsername',
        'name' => 'setName',
        'summary' => 'setSummary',
        'twitterUsername' => 'setTwitterUsername',
        'githubUsername' => 'setGithubUsername',
        'url' => 'setUrl',
        'location' => 'setLocation',
        'techStack' => 'setTechStack',
        'tagLine' => 'setTagLine',
        'story' => 'setStory',
        'joinedAt' => 'setJoinedAt',
        'profileImage' => 'setProfileImage'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'typeOf' => 'getTypeOf',
        'username' => 'getUsername',
        'name' => 'getName',
        'summary' => 'getSummary',
        'twitterUsername' => 'getTwitterUsername',
        'githubUsername' => 'getGithubUsername',
        'url' => 'getUrl',
        'location' => 'getLocation',
        'techStack' => 'getTechStack',
        'tagLine' => 'getTagLine',
        'story' => 'getStory',
        'joinedAt' => 'getJoinedAt',
        'profileImage' => 'getProfileImage'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['typeOf'] = $data['typeOf'] ?? null;
        $this->container['username'] = $data['username'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['summary'] = $data['summary'] ?? null;
        $this->container['twitterUsername'] = $data['twitterUsername'] ?? null;
        $this->container['githubUsername'] = $data['githubUsername'] ?? null;
        $this->container['url'] = $data['url'] ?? null;
        $this->container['location'] = $data['location'] ?? null;
        $this->container['techStack'] = $data['techStack'] ?? null;
        $this->container['tagLine'] = $data['tagLine'] ?? null;
        $this->container['story'] = $data['story'] ?? null;
        $this->container['joinedAt'] = $data['joinedAt'] ?? null;
        $this->container['profileImage'] = $data['profileImage'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets typeOf
     *
     * @return string|null
     */
    public function getTypeOf()
    {
        return $this->container['typeOf'];
    }

    /**
     * Sets typeOf
     *
     * @param string|null $typeOf typeOf
     *
     * @return self
     */
    public function setTypeOf($typeOf)
    {
        $this->container['typeOf'] = $typeOf;

        return $this;
    }

    /**
     * Gets username
     *
     * @return string|null
     */
    public function getUsername()
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string|null $username username
     *
     * @return self
     */
    public function setUsername($username)
    {
        $this->container['username'] = $username;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets summary
     *
     * @return string|null
     */
    public function getSummary()
    {
        return $this->container['summary'];
    }

    /**
     * Sets summary
     *
     * @param string|null $summary summary
     *
     * @return self
     */
    public function setSummary($summary)
    {
        $this->container['summary'] = $summary;

        return $this;
    }

    /**
     * Gets twitterUsername
     *
     * @return string|null
     */
    public function getTwitterUsername()
    {
        return $this->container['twitterUsername'];
    }

    /**
     * Sets twitterUsername
     *
     * @param string|null $twitterUsername twitterUsername
     *
     * @return self
     */
    public function setTwitterUsername($twitterUsername)
    {
        $this->container['twitterUsername'] = $twitterUsername;

        return $this;
    }

    /**
     * Gets githubUsername
     *
     * @return string|null
     */
    public function getGithubUsername()
    {
        return $this->container['githubUsername'];
    }

    /**
     * Sets githubUsername
     *
     * @param string|null $githubUsername githubUsername
     *
     * @return self
     */
    public function setGithubUsername($githubUsername)
    {
        $this->container['githubUsername'] = $githubUsername;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets location
     *
     * @return string|null
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param string|null $location location
     *
     * @return self
     */
    public function setLocation($location)
    {
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets techStack
     *
     * @return string|null
     */
    public function getTechStack()
    {
        return $this->container['techStack'];
    }

    /**
     * Sets techStack
     *
     * @param string|null $techStack techStack
     *
     * @return self
     */
    public function setTechStack($techStack)
    {
        $this->container['techStack'] = $techStack;

        return $this;
    }

    /**
     * Gets tagLine
     *
     * @return string|null
     */
    public function getTagLine()
    {
        return $this->container['tagLine'];
    }

    /**
     * Sets tagLine
     *
     * @param string|null $tagLine tagLine
     *
     * @return self
     */
    public function setTagLine($tagLine)
    {
        $this->container['tagLine'] = $tagLine;

        return $this;
    }

    /**
     * Gets story
     *
     * @return string|null
     */
    public function getStory()
    {
        return $this->container['story'];
    }

    /**
     * Sets story
     *
     * @param string|null $story story
     *
     * @return self
     */
    public function setStory($story)
    {
        $this->container['story'] = $story;

        return $this;
    }

    /**
     * Gets joinedAt
     *
     * @return \DateTime|null
     */
    public function getJoinedAt()
    {
        return $this->container['joinedAt'];
    }

    /**
     * Sets joinedAt
     *
     * @param \DateTime|null $joinedAt Date of joining
     *
     * @return self
     */
    public function setJoinedAt($joinedAt)
    {
        $this->container['joinedAt'] = $joinedAt;

        return $this;
    }

    /**
     * Gets profileImage
     *
     * @return string|null
     */
    public function getProfileImage()
    {
        return $this->container['profileImage'];
    }

    /**
     * Sets profileImage
     *
     * @param string|null $profileImage Profile image (640x640)
     *
     * @return self
     */
    public function setProfileImage($profileImage)
    {
        $this->container['profileImage'] = $profileImage;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


